export const SIGNUP = "SIGNUP";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const NO_MORE_NOTIFICATIONS = "NO_MORE_NOTIFICATIONS";
export const ADD_NOTIFICATIONS = "ADD_NOTIFICATIONS";
export const UPDATE_PROFILE_NAME = "UPDATE_PROFILE_NAME";
export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE";
export const WELCOME_PAGE_SEEN = "WELCOME_PAGE_SEEN";
export const ADD_PHONE_NUMBER = "ADD_PHONE_NUMBER";
export const NEW_NOTIFICATION = "NEW_NOTIFICATION";
export const UPDATE_USER = "UPDATE_USER";
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const SHUFFLE_LOGIN = "SHUFFLE_LOGIN";


